# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Alexandre/Desktop/mult_pico_blazer_display/mult_pico_blazer.cache/wt [current_project]
set_property parent.project_path C:/Users/Alexandre/Desktop/mult_pico_blazer_display/mult_pico_blazer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Alexandre/Desktop/mult_pico_blazer_display/mult_pico_blazer.srcs/sources_1/imports/Desktop/Decodificador.vhd
  C:/Users/Alexandre/Desktop/mult_pico_blazer_display/mult_pico_blazer.srcs/sources_1/imports/VHDL/kcpsm6.vhd
  C:/Users/Alexandre/Desktop/mult_pico_blazer_display/mult_pico_blazer.srcs/sources_1/imports/Assembler/multiplicador.vhd
  C:/Users/Alexandre/Desktop/mult_pico_blazer_display/mult_pico_blazer.srcs/sources_1/new/top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Alexandre/Desktop/mult_pico_blazer_display/mult_pico_blazer.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Alexandre/Desktop/mult_pico_blazer_display/mult_pico_blazer.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc]


synth_design -top top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
